# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 510)
        MainWindow.setMinimumSize(QtCore.QSize(1, 0))
        MainWindow.setStyleSheet(" background-repeat: no-repeat;\n"
"/*background-image: url(C://Users//Ahmed Taha//Downloads//background.png);*/\n"
"background-size: contain;\n"
"background-color: #1D5181;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LungImagelabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LungImagelabel.sizePolicy().hasHeightForWidth())
        self.LungImagelabel.setSizePolicy(sizePolicy)
        self.LungImagelabel.setMinimumSize(QtCore.QSize(310, 300))
        self.LungImagelabel.setMaximumSize(QtCore.QSize(310, 300))
        self.LungImagelabel.setStyleSheet("color: white;\n"
"background-color: #33628d;\n"
"border-radius:20px")
        self.LungImagelabel.setText("")
        self.LungImagelabel.setPixmap(QtGui.QPixmap("Images/RedLungs.png"))
        self.LungImagelabel.setScaledContents(True)
        self.LungImagelabel.setObjectName("LungImagelabel")
        self.horizontalLayout_5.addWidget(self.LungImagelabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FVClabel = QtWidgets.QLabel(self.centralwidget)
        self.FVClabel.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FVClabel.setFont(font)
        self.FVClabel.setStyleSheet("color: white;\n"
"background-image:white;\n"
"background-color: #133453;\n"
"border-radius:20px")
        self.FVClabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FVClabel.setObjectName("FVClabel")
        self.horizontalLayout_2.addWidget(self.FVClabel)
        self.FVC = QtWidgets.QLabel(self.centralwidget)
        self.FVC.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FVC.setFont(font)
        self.FVC.setStyleSheet("color: white;\n"
"background-image:white;\n"
"background-color: #133453;\n"
"border-radius:20px")
        self.FVC.setAlignment(QtCore.Qt.AlignCenter)
        self.FVC.setObjectName("FVC")
        self.horizontalLayout_2.addWidget(self.FVC)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FEFlabel = QtWidgets.QLabel(self.centralwidget)
        self.FEFlabel.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FEFlabel.setFont(font)
        self.FEFlabel.setStyleSheet("color: white;\n"
"background-image:white;\n"
"background-color: #133453;\n"
"border-radius:20px")
        self.FEFlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.FEFlabel.setObjectName("FEFlabel")
        self.horizontalLayout_3.addWidget(self.FEFlabel)
        self.FEF = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FEF.setFont(font)
        self.FEF.setStyleSheet("color: white;\n"
"background-image:white;\n"
"background-color: #133453;\n"
"border-radius:20px")
        self.FEF.setAlignment(QtCore.Qt.AlignCenter)
        self.FEF.setObjectName("FEF")
        self.horizontalLayout_3.addWidget(self.FEF)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.PEFRlabel = QtWidgets.QLabel(self.centralwidget)
        self.PEFRlabel.setMinimumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PEFRlabel.setFont(font)
        self.PEFRlabel.setStyleSheet("color: white;\n"
"background-image:white;\n"
"background-color: #133453;\n"
"border-radius:20px")
        self.PEFRlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PEFRlabel.setObjectName("PEFRlabel")
        self.horizontalLayout_4.addWidget(self.PEFRlabel)
        self.PEFR = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PEFR.setFont(font)
        self.PEFR.setStyleSheet("color: white;\n"
"background-image:white;\n"
"background-color: #133453;\n"
"border-radius:20px")
        self.PEFR.setAlignment(QtCore.Qt.AlignCenter)
        self.PEFR.setObjectName("PEFR")
        self.horizontalLayout_4.addWidget(self.PEFR)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FlowGraph = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlowGraph.sizePolicy().hasHeightForWidth())
        self.FlowGraph.setSizePolicy(sizePolicy)
        self.FlowGraph.setStyleSheet("background-color: #133453;\n"
"Border: none;")
        self.FlowGraph.setObjectName("FlowGraph")
        self.horizontalLayout.addWidget(self.FlowGraph)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.FlowValue = QtWidgets.QLabel(self.centralwidget)
        self.FlowValue.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.FlowValue.setFont(font)
        self.FlowValue.setStyleSheet("color: white;\n"
"background-image:white;\n"
"background-color: #133453;\n"
"border-radius:20px")
        self.FlowValue.setAlignment(QtCore.Qt.AlignCenter)
        self.FlowValue.setObjectName("FlowValue")
        self.horizontalLayout.addWidget(self.FlowValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FVClabel.setText(_translate("MainWindow", "FVC"))
        self.FVC.setText(_translate("MainWindow", "%"))
        self.FEFlabel.setText(_translate("MainWindow", "FEF"))
        self.FEF.setText(_translate("MainWindow", "%"))
        self.PEFRlabel.setText(_translate("MainWindow", "PEFR"))
        self.PEFR.setText(_translate("MainWindow", "%"))
        self.FlowValue.setText(_translate("MainWindow", "Flow"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
